### ISSUE TITLE
How to Hide cookie banner?

### ISSUE THREAD

**Issue by bugattie** [tcampb/react-calendly#100]
Hi,
I'm using react-calendly for a gatsby site, and it's working fine. My client wants me to remove [this cookie banner](https://drive.google.com/file/d/1nioYAfmhsFkRabaYDJfrfFPKEWgapRx9/view?usp=sharing) for the calendly, as we're using gatsby-plugin-gdpr-cookies for GDPR Cookies.

I tried this [Link](https://help.calendly.com/hc/en-us/articles/223147027-Embed-options-overview?tab=advanced#hiding-the-cookie-banner-in-the-embed-0-7)

It doesn't work, So I look for other ways I found one,
`openPopupWidget({
      url: "https://calendly.com/-------",
      pageSettings: {
        hideGdprBanner: true,
      },
    })`

But it doesn't work either, is there any other ways to remove the cookie banner?

**Comment by tcampb** [comment]
@bugattie can you confirm that the iframe url's query parameters includes `hide_gdpr_banner=1`? When I clicked "Schedule a call" on your site I initially saw the Calendly cookie banner since the iframe url did not include the query parameter above; however, after manually adding the query parameter to the url the banner disappeared.

**Comment by bugattie** [comment]
Thank you @tcampb. I now no longer getting the banner by your method
