### ISSUE TITLE
I'd like the iframe to always take as much height as needed, without generating a vertical scrollbar

### ISSUE THREAD

**Issue by afcjunior** [tcampb/react-calendly#137]
Any ideas on how to achieve this? Specifically with the `<InlineWidget />`.

- I tried wrapping it and overriding the styles with height: auto or height 100% and it still doesn't grow by itself if I dont set a fixed height at some point.
- I then tried changing the height based on the viewport width with media queries. The problem with this one is that the required height of the iFrame varies depending on its content. So for example, when I made a fixed height for viewport width 320px, if I navigated onto the calendar view, I would have a lot of empty white space below the calendar pushing down the content i'd like to show close by.

**Comment by tcampb** [comment]
The only workaround I can think of would be to render the event type's available time slots in your web application's UI instead of using the iframe (you can use [Calendly's api to retrieve this information](https://developer.calendly.com/api-docs/6a1be82aef359-list-event-type-available-times)).

Once the user selects a date / time, you could then show the iframe with the scheduling form for the selected date / time.

**Comment by tcampb** [comment]
@afcjunior -

Version 4.3.1 updates the  `useCalendlyEventListener` hook to include an `onPageHeightResize` option.

This allows you to resize the parent container when the Calendly scheduling page's height changes. 

For example:

```jsx
import {
  InlineWidget,
  useCalendlyEventListener,
} from "react-calendly";

function App() {
  const [height, setHeight] = useState('500px');
  const onPageHeightResize = (e) => setHeight(e.data.payload.height);

  useCalendlyEventListener({
    onPageHeightResize
  })

  return (
    <>
      <InlineWidget
        styles={{ height }}
        url="https://calendly.com/acmesales"
      />
    </>
  );
}
```
