### ISSUE TITLE
TypeScript : rootElement "Type 'HTMLElement | null' is not assignable to type 'HTMLElement'."

### ISSUE THREAD

**Issue by daliovic** [tcampb/react-calendly#139]
Even though everything seems to be working fine, VS Code is just not happy with the return type of getElementByID. 
(I am new to TypeScript, adding "as HTMLElement" after document.getElementById('root') seems to fix the issue)

**Comment by tcampb** [comment]
@daliovic - since an element may not exist with an id of `root`, it's possible for `document.getElementById('root')` to return `null`, which as you mentioned is incompatible with the `rootElement` type. 

I typically use the `as HTMLElement` type assertion that you mentioned to let the compiler know that an element with an id of `root` will be available at runtime. Since this type assertion tells the compiler that the element will **not** be `null` at runtime, the type is now compatible.

If you'd prefer not to use the type assertion keyword, you can instead conditionally render the component:

```javascript
const rootElement = document.getElementById("root");

if (!rootElement) {
   return null;
} 

return (
      <PopupWidget
        url="https://calendly.com/your_scheduling_page"
        /*
         * react-calendly uses React's Portal feature (https://reactjs.org/docs/portals.html) to render the popup modal. As a result, you'll need to
         * specify the rootElement property to ensure that the modal is inserted into the correct domNode.
         */
        rootElement={rootElement}
        text="Click here to schedule!"
        textColor="#ffffff"
        color="#00a2ff"
      />
)
```

This should also fix the compiler error since we ensure that `rootElement` is not null when the component is rendered.
