### ISSUE TITLE
change the iFrame background-color

### ISSUE THREAD

**Issue by JackYouk** [tcampb/react-calendly#147]
Everytime I try to change the background color of the iframe it defaults back to white, making it look really ugly within my app. Using the pro version, wish I could change it because I might have to re-engineer the widget altogether.

**Comment by tcampb** [comment]
@JackYouk - could you share the Calendly link you are using for testing? I wasn't able to recreate the error locally; for example, in this [stackblitz example](https://stackblitz.com/edit/react-ts-wfqsuk?file=App.tsx) the background color was changed.

**Comment by JackYouk** [comment]
![Screen Shot 2023-03-10 at 6 02 03 PM](https://user-images.githubusercontent.com/102705118/224459094-0539109e-5a64-470d-9c26-7c21ca85e698.png)

Not talking about the background of the widget, but the white background on the iframe

**Comment by JackYouk** [comment]
When I change the iframe background-color to black for example, it will flash black upon render and then default back to white

**Comment by tcampb** [comment]
Thanks for the additional details and screenshot. I tried changing the color parameter for a non-embedded Calendly page and saw the same behavior. 

For example, if you visit [https://calendly.com/acmesales?background_color=aaaaaa](https://calendly.com/acmesales?background_color=aaaaaa) directly you'll see that background color only applies to the scheduling calendar's background, not the actual page background.

Since Calendly's background_color query parameter does not support changing the background color of the page, the only workaround I can think of is to set the width of the widget to less than 650px so that it is loaded in the mobile view (which removes the white background).

**Comment by JackYouk** [comment]
Thanks that works perfect

**Comment by RafaelZasas** [comment]
Is there any solutions to this? Ideally one would just set the background to transparent or the background color of the website and let the widget grow as needed.

Ive been messing with height and width css properties all day and cant get it to the point where it looks and feels like an actual part of the website, unless I allow the white background

**Comment by ArsenicBismuth** [comment]
This shouldn't be an issue as the official examples handle iframe background nicely.

See here: https://www.calendly-embed.com/pop-up-text-2/

The pop-up iframe has transparent background, and it actually works nicely. But it's completely white in React.

Below are some previews across the 3 different methods (pink to showcase the transparency).
![image](https://github.com/tcampb/react-calendly/assets/19264532/8001d8fd-3b8a-4221-b36f-d661147892ee)

![image](https://github.com/tcampb/react-calendly/assets/19264532/3cb43972-749b-4593-abf4-7b6eda369c07)

![image](https://github.com/tcampb/react-calendly/assets/19264532/b7a1e414-7a5a-4f6a-ba1d-894620c053a5)

**Comment by JackYouk** [comment]
Would be nice if the styles could be more customizable with the premium calendly sub... just went ahead and built my own ui and integrated with the api back when I brought up this issue because the styling wasn't flexible enough for me to match the style my client wanted.
