### ISSUE TITLE
Redirect Modal

### ISSUE THREAD

**Issue by emreonursoy** [tcampb/react-calendly#148]
Redirect modal after creating event changes iframe width on iPhone

**Comment by tcampb** [comment]
Hey @emreonursoy,

Unfortunately, this is not something we can change within the `react-calendly` library as we cannot change the iframe content's width dynamically based on the parent window's width. 

One option would be to use the [useCalendlyEventListener](https://github.com/tcampb/react-calendly#usecalendlyeventlistener) hook to detect when the event is scheduled. You could then perform the external redirect from the parent site instead of within the iframe.

**Comment by emreonursoy** [comment]
Your eventListeners are not fully compatible with re-schedule and cancel unfortunately.

**Comment by tcampb** [comment]
According to the Calendly support team (see [here](https://github.com/tcampb/react-calendly/issues/125)), the Calendly embed does not currently support canceled / rescheduled events. Once support is added for canceled / rescheduled events I'll reopen this issue to track adding the feature to `react-calendly`.
