### ISSUE TITLE
Errors appearing in console.

### ISSUE THREAD

**Issue by Joxnt** [tcampb/react-calendly#154]
Hello!
I will admit that I am new to react so I may just have been being a tad silly, I am getting the follwing errors and have been unable to do anything about it.

![image](https://github.com/tcampb/react-calendly/assets/84520213/5fc788c2-568f-42db-a07a-a1cecac733e9)

The integration works but I would very much like to be rid of the errors showing up in the console to maintain the appearance of a well put together website.

I am using the latest version of the package and also have tailwind and vite in my project if that helps. I have also been running this with `npm run dev`

```
import React from 'react'
import { InlineWidget } from 'react-calendly'

const Calendly = () => {
  return (
    <InlineWidget url="https://calendly.com/hrmolyneux/free-consultation" />
  )
}

export default Calendly
```

**Comment by tcampb** [comment]
Hey @Joxnt, 

These errors appear to be coming from Calendly's booking page rather than the `react-calendly` library. However, I believe these errors will disappear when you deploy your app to a site using `https` instead of `http`.

For example, when you load the popup widget on the https site [here](https://tcampb.github.io/react-calendly/?path=/story/components--popupwidget) no console warnings / errors appear.

**Comment by Joxnt** [comment]
@tcampb 
Thank you for the swift reply and the helpful information.

As I am quite a way away from making my website live, and do not yet posess an SSL certificate, I won't be able to test your theory.

Is there an alternate way to try with `https` that i am not aware of?

If not, you can close the issue or do whatever you'd like with it.

Thank you.

**Comment by tcampb** [comment]
Hey @Joxnt,

While you can setup [localhost to use https](https://www.freecodecamp.org/news/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec/), I like to use [ngrok](https://ngrok.com).

They have a free version that let's you access localhost over a public https url that they generate for you. Based on your screenshot, it looks like you're using port 5173. After installing ngrok you can run the following command:

```bash
ngrok http 5173
```

The command above will then return an https url you can use to access localhost.

**Comment by Joxnt** [comment]
Hi @tcampb
Thank you for the help so far,
running my build preview through ngrok has not solved the issue. I am still getting the exact same error as with using localhost.

Here are the errors, using a build preview has solved a couple of the errors i was recieving:
![image](https://github.com/tcampb/react-calendly/assets/84520213/cd267f73-aeac-4b49-8d95-b84e0a3a04d8)

**Comment by tcampb** [comment]
Thanks for trying the `https` route; I was able to re-create the errors / warnings in firefox, but not in chrome or safari. Unfortunately, I don't think there is anything we can do within the `react-calendly` library to prevent these errors from occurring since they are coming from Calendly's code.

That said, these errors should not cause issues when scheduling an event through the popup widget.

**Comment by Joxnt** [comment]
Thank you for your help.
