### ISSUE TITLE
Support for Smaller Screen Sizes?

### ISSUE THREAD

**Issue by shane01101** [tcampb/react-calendly#16]
Is it possible to apply styles so the calendar widget is responsive on smaller screen sizes when using the InlineWidget? When I apply height or width css properties, I can't get rid of the vertical scrollbar.

**Comment by tcampb** [comment]
Hi @shane01101,

The scrollbar appears when the iframe content's height exceeds the height of the parent container. Unfortunately, this is not something we can change within the `react-calendly` library as we cannot change the iframe content's height dynamically based on the parent window's height. That said, this issue has been brought up on Calendly's idea portal and I would encourage you to upvote the idea [here](https://help.calendly.com/hc/en-us/community/posts/360032035073-Iframe-Resize-Parent-Window-Content-Height-Prevent-Double-Scroll-Bar).

**Comment by ryanovas** [comment]
Is there no way to use something like this? https://github.com/davidjbradshaw/iframe-resizer-react

Managing the vertical scrollbar on the inline widget is a real pain

**Comment by ryanovas** [comment]
Yea I realized after I commented that it's calendly making things weird. Shoulda researched more before commenting! Shame though, doesn't make it less of a pain

On Wed, Jan 05, 2022 at 12:51pm, Tyler Campbell ***@***.***> wrote:
@ryanovas - it looks like the library you linked resizes the iframe by using window.postMessage to communicate with the iframe content window.
For this to work, Calendly would need to change the code on their end to accept messages from the parent window to resize the page. Without this change any messages sent to the iframe content window would be ignored.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/tcampb/react-calendly/issues/16#issuecomment-1005944220",
"url": "https://github.com/tcampb/react-calendly/issues/16#issuecomment-1005944220",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
