### ISSUE TITLE
Hide landing page and event details reappears on schedule event

### ISSUE THREAD

**Issue by recodedecode** [tcampb/react-calendly#162]
Hi there, thank you for this library.

This is likely not a problem with the `react-calendly` library but wanted to check in case there's some config that I've missed.

The `hideEventTypeDetails` and `hideLandingPageDetails` both work initially but then on the final screen after selecting a date and time the detail panel reappears.

This is not a duplicate of #55 as the properties both work as expected at least initially.

```jsx
  <InlineWidget
    pageSettings={{
      hideEventTypeDetails: true,
      hideLandingPageDetails: true,
    }}
    url="https://calendly.com/xyz/event-x" />
```

**Comment by tcampb** [comment]
Hey @recodedecode, I was also able to recreate this issue using Calendly's default embed. Based on the `hide_event_type_details` description it sounds like this is the expected behavior. That said, I agree that this is confusing since the main use case here is to hide the branding in the iframe.

I would recommend reaching out to Calendly's support team (support@calendly.com) to share your feedback.

**Comment by recodedecode** [comment]
Thanks, appreciate the feedback. 👍
