### ISSUE TITLE
useCalendlyEventListener fires multiple times

### ISSUE THREAD

**Issue by zpydee** [tcampb/react-calendly#168]
Perhaps I am using it wrong, ut I find that event fire 6 times for every event?

```
type Props = {
  calendlyUrl: string;
};

export const CalendlyForm = ({ calendlyUrl }: Props) => {
  useCalendlyEventListener({
    onDateAndTimeSelected: () =>
      window.gtag('event', 'calendly_select_date_and_time'),
    onEventScheduled: (e) =>
      window.gtag('event', 'calendly_event_scheduled', {
        payload: e.data.payload,
      }),
  });
  return (
    <>
      <div className="modal-content h-[600px] hidden md:flex px-8  gap-16 text-left ">
        <div className="flex-1">
          <DiscoverySession />
        </div>
        <InlineWidget
          url={calendlyUrl}
          styles={{ height: '600px' }}
          pageSettings={{ hideEventTypeDetails: true }}
        />
      </div>
      <div className="modal-content h-[480px] block md:hidden">
        <InlineWidget
          url={calendlyUrl}
          styles={{ height: '480px' }}
          pageSettings={{ hideEventTypeDetails: true }}
        />
      </div>
    </>
  );
};
```

**Comment by tcampb** [comment]
Hey @zpydee - the `useCalendlyEventListener` hook adds a global event listener each time it is used. Are you rendering multiple `CalendlyForm` components at the same time?

Also, I noticed that you're using Google Analytics in the hook callback. Is there a particular reason you are using the hook callback instead of Calendly's built-in Google Analytics integration?

https://help.calendly.com/hc/en-us/articles/360001575393-Getting-started-with-Google-Analytics#getting-started-with-google-analytics-0-0

**Comment by zpydee** [comment]
that would explain it. is there a workaround?

I'm not using the calendly integration beuuase it only allows a single G-TAG. i have multiple landing pages to track. It would be helpful if they cpould move the integration to an event level.

**Comment by tcampb** [comment]
Could you try moving the hook out of the `CalendlyForm` so that the event listener is only called once?

**Comment by zpydee** [comment]
yeah, i'll try that in the morning. thanks

**Comment by zpydee** [comment]
sorted. I created a `CalendlyEvents` Component to house the hook and added that to my layout. thanks.
