### ISSUE TITLE
Is it possible to get update about the height of the Calendly widget?

### ISSUE THREAD

**Issue by ljs19923** [tcampb/react-calendly#174]
Hello, 

Is it possible to get update about the height of the Calendly widget?

I want to integrate the Calendly in my page without to have an inline scroll, so I want to know everytime the height of the iframe/widget Calendly.

Thanks a lot

**Comment by tcampb** [comment]
Unfortunately, this is not something we can detect within the `react-calendly` library since the Calendly iframe does not post a message when the content is resized.

That said, Calendly's public api released an endpoint that allows you to retrieve the available time slots by event type, so it's possible that you could change the height based on the number of available times returned by the api.

[https://developer.calendly.com/api-docs/6a1be82aef359-list-event-type-available-times](https://developer.calendly.com/api-docs/6a1be82aef359-list-event-type-available-times)

**Comment by tcampb** [comment]
@ljs19923 @jketcham -

Version 4.3.1 updates the  `useCalendlyEventListener` hook to include an `onPageHeightResize` option.

This allows you to resize the parent container when the Calendly scheduling page's height changes. 

For example:

```jsx
import {
  InlineWidget,
  useCalendlyEventListener,
} from "react-calendly";

function App() {
  const [height, setHeight] = useState('500px');
  const onPageHeightResize = (e) => setHeight(e.data.payload.height);

  useCalendlyEventListener({
    onPageHeightResize
  })

  return (
    <>
      <InlineWidget
        styles={{ height }}
        url="https://calendly.com/acmesales"
      />
    </>
  );
}
```
