### ISSUE TITLE
White space in the iframe embedding

### ISSUE THREAD

**Issue by shengha2** [tcampb/react-calendly#176]
We were trying to embed calendly into our widget but it has some whitespace underneath.
Check out:https://www.loom.com/share/c1498f86df2d4bc2b9ad41dbed7e775d?sid=4c00faf2-132e-4595-997d-7e8a1da01d96&fbclid=IwAR1aKGEupQJd0az07-D9u4tZydSDdsXbo4v8knbbOR56-EAQKTdzTwkl06g

**Comment by tcampb** [comment]
Hey @shengha2, thanks for sharing the loom video, it's really helpful to understand the issue your team is running into. Unfortunately, we are really limited in terms of customization since it's using an iframe. 

The only workaround I can think of is to use the event type api to retrieve the event type's available times and render your own custom components.

https://developer.calendly.com/api-docs/6a1be82aef359-list-event-type-available-times
