### ISSUE TITLE
Implement react-calandely embeded 

### ISSUE THREAD

**Issue by dilipsingh076** [tcampb/react-calendly#191]
![image (3)](https://github.com/user-attachments/assets/779d87f0-acbc-451f-a8dd-5d1b8145b9d8)
![image (4)](https://github.com/user-attachments/assets/11e47aea-8af9-4d08-878b-b663b290b9dc)

![image (5)](https://github.com/user-attachments/assets/328d74fe-1f1a-45d4-9382-1d80fb08f179)
![image (6)](https://github.com/user-attachments/assets/7c09633b-02ee-4a7f-8446-47df0e80272f)

I Implemented react-calandely version 4.3.1  in my application after click on the **schedule the valuable consentent** Button 
 react-calandely get triggered and after that loading start on the window and new model open.

there are 3 methods to implemnet react-calandely so i perefer that **Pop-up widget** here i am sharing that link with you.
https://www.calendly-embed.com/embed-popupwidget

After click on that button new Modal come on the screen with loading feature I try so many methods to avoide the loading but i am unable to achive this feature i want that after click on that button modal come directly on the screen without any loading.

Everything is working great as per the expectation but in this i want to avoide the loading which come after hit the button it is a part of calandely i try so many menthods but i failed to stop loading i want that calandely come on the screeen without loading 

Please help me to achive this behaviour that how we can achive this.

I added all the screenshot for better understanding.
email : dilipsinghf@gmail.com

**Comment by tcampb** [comment]
Hey @dilipsingh076 - thanks for the screenshots and detailed Github issue. Since the Calendly embed uses an iframe, the loading spinner appears while the iframe is loading the Calendly scheduling page.

The only workaround I can think of would be to render an iframe with an opacity set to 0 so that the user does not see it, as described in this [stackoverflow post](https://stackoverflow.com/a/32548303/13641812).

Note that this use case is not supported by react-calendly, so you'd need to use an iframe tag to load your Calendly scheduling page.

```jsx
<iframe src="https://calendly.com/acmesales"></iframe>
```
