### ISSUE TITLE
Error on Deploy in Netlify

### ISSUE THREAD

**Issue by heysoypaez** [tcampb/react-calendly#2]
Hi Friend.

I have the following problem with your package:

In local development works fine but when i deploy my gatsby project on netlify it give me an error:

`WebpackError: ReferenceError: window is not defined`

related with this line of code ` var Calendly = window ? window.Calendly : {};`

I decided to create a local component but if you can fix that it will be amazing.

Notes: netlify says it error is related with the fact that in the server the window variable does not exist and this have total sense.

**Comment by tcampb** [comment]
This should be fixed now, thanks for catching this!

https://github.com/tcampb/react-calendly/pull/5

**Comment by rinorzek** [comment]
@tcampb I think this is happening again, could you please help? I'm using the newest version 2.2.2 it was working before but now when deployed with netlify it doesn't show the calendar.

**Comment by tcampb** [comment]
@rinorzek - is your application failing to deploy, or is it deploying successfully but the Calendly widget is not working on the live site? Also, what version were you previously using that worked? 

If you could share a link to the repository that would be helpful; or if it's a private repository you can just share the code block that is using the react calendly component.

**Comment by rinorzek** [comment]
@tcampb thank for the reply, no in fact it gets deployed successfully, and the weird thing is that when I build and serve it locally it works, but not when deployed in netlify. And also I was using the same version a month ago when it worked, but now it's doesn't 😞 . Here is what I have in code for it.
`{data.enablePopupWidget && (
        <PopupWidget
          branding={data.calendlyBranding}
          color={data.calendlyWidgetColor?.hex}
          text={data.calendlyWidgetText}
          textColor="#ffffff"
          url={data.calendlyUrl}
        />
      )}`
since I'm getting those from a cms, I also tried hardcoding those values, but same result works in local build but not in Netlify. One more thing is that the widget actually shows but when I click that, the displays the backdrop with the loading dots for like a second but the calendar modal never shows up. Hope that I didn't complicate that much 😄

**Comment by tcampb** [comment]
Thanks for the additional information @rinorzek. Can you confirm that the Calendly url prop is using **https** (example: https://calendly.com/acmesales)? Since this issue only occurs in production, I'm wondering if it's related to a CORS error or if the iframe src url is not prefixed with https. 

Also, would you be able to share a link to a live netlify app that is having the issue currently?

**Comment by rinorzek** [comment]
@tcampb yes, the url has the https prefix, and sure you can check it [here](https://transcend.io/contact/)

**Comment by tcampb** [comment]
@rinorzek - I think I found the issue; I'm currently working on a fix and I'll let you know once it's ready.

**Comment by tcampb** [comment]
@rinorzek - When viewing the link above (https://transcend.io/contact/) it appears that the Calendly widget is currently working. Were you able to fix the issue?

**Comment by rinorzek** [comment]
@tcampb actually one thing I noticed is that the popup is working on my phone, but not in my laptop. Not sure now if this issue is device/browser related 😞 .

**Comment by rinorzek** [comment]
@tcampb sorry for mentioning it again, have you found anything that is causing that?

**Comment by tcampb** [comment]
@rinorzek - Unfortunately I've not been able to look into the issue further since I haven't been able to re-create the issue. I've tested the link above using both Safari and Chrome on my laptop; are there any specific steps I should follow to re-create the error? Also, could you try enabling the "Disable Cache" setting in the network tab and reload the page?

![image](https://user-images.githubusercontent.com/33756113/145987372-28a7aed3-5af5-407b-9cb5-ef2e086a9b69.png)


![image](https://user-images.githubusercontent.com/33756113/145986769-23ccdbaf-2d63-4ab4-9294-17a7dc1e2d8e.png)

**Comment by rinorzek** [comment]
@tcampb for me it works on safari but the modal doesn't open in chrome, I saw that this doesn't happen only to me but to my teammates as well. Not sure if a chrome version has to do with it.
![Screen Shot 2021-12-14 at 16 12 13](https://user-images.githubusercontent.com/78733927/146025370-42b8cb63-835f-4c82-b6db-2e9890f3b6ea.png)

**Comment by tcampb** [comment]
@rinorzek - what version of chrome are you using? Also, are you using any chrome extensions that might be blocking the iframe?

**Comment by rinorzek** [comment]
@tcampb I'm using the 96.0.4664.110 version of chrome, and I check also in an incognito window to not be effected by extensions but the issue still persists.

**Comment by tcampb** [comment]
@rinorzek - Thanks for confirming the chrome version. Unfortunately, I was unable to re-create this error when using the same chrome version on both my Windows PC and macOS device. Without being able to re-create the error my best guess would be that this is due to some type of race condition since this package uses a javascript file from Calendly to create the widget (see [here](https://github.com/tcampb/react-calendly/blob/master/src/calendly-widget.ts)).

You may want to try creating the iframe directly in your React code:

```typescript
() = > <iframe src="CALENDLY_URL" width="100%" height="100%" frameborder="0"></iframe>
```
