### ISSUE TITLE
The loaded css contains generic rules

### ISSUE THREAD

**Issue by DevAlien** [tcampb/react-calendly#63]
Great job here, the only issue I have is that the included CSS loaded from calendly is adding rules for body: `html,body{height:100%}body{overflow:auto}` I don't think this should be part of the included css

**Comment by tcampb** [comment]
Hi @DevAlien -

I agree that the current css rules should not change the `html` and `body` tag styles. The current implementation simply loads the most recent version of the Calendly widget css (see [here](https://github.com/tcampb/react-calendly/blob/master/src/calendly.tsx#L99-L106)) and I was hesitant to try and override their css rules. 

Would it help to add an option to `react-calendly` that prevents loading Calendly's default stylesheet so that you can provide your own?

**Comment by DevAlien** [comment]
Could be an option, but I don't see why anyone would want that css on html and body.

**Comment by tcampb** [comment]
Hi @DevAlien, 

I just published a new version (2.0.2) that includes the calendly widget css file with `html,body{height:100%}body{overflow:auto}` removed.

https://github.com/tcampb/react-calendly/pull/66/files

Hope this helps, thanks for creating this Github issue!

**Comment by DevAlien** [comment]
That's great, tomorrow i will test it. I think this was the way to. Of course we have to keep an eye on their css I'd it changes
